[m3] slap track_caller on assert_balanced
What this does is it improves the experience when running without RUST_BACKTRACE
=1.

Specifically, if we changed the collatz example to pull 2 instead of 1, we
would get the panic message below. Note the source of panic, it points to the
collatz code rather than the Channel code.

    thread 'model::test_collatz_high_level_validation' panicked at crates/m3/tests/collatz.rs:53:27:
    Channel is not balanced:
      Unbalanced pushes:
        1: 1
      Unbalanced pulls:
        1: 2